action_id: trunk-cache-prune
date: 2025-11-06 10:31:41
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1762425101
full_timestamp:
  nanos: 879531000
  seconds: 1762425101
trunk_version: 1.25.0
