action_id: trunk-cache-prune
date: 2025-11-08 17:54:00
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1762624440
full_timestamp:
  nanos: 991264000
  seconds: 1762624440
trunk_version: 1.25.0
