### Login citizen
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "dellar@gmail.com",
  "password": "Franklin@123"
}

### Register citizen
POST http://localhost:3000/api/register/citizen
Content-Type: application/json

{
  "email": "dellar@gmail.com",
  "password": "Franklin@123",
  "firstname": "Della",
  "lastname": "Raolane",
  "locationAddress": "226 west street"
}


### Send Water Outage Notification
POST http://localhost:3000/api/notifications/send
Content-Type: application/json

{
  "room": "RoseGarden",
  "type": "Water Outage",
  "message": "Water outage from 2 PM to 6 PM"
}

POST http://localhost:3000/api/lodgequery
Content-Type: application/json

  {
  "type": "dellar@gmail.com",
  "subtype": "Franklin@123",
  "name": "Della",
  "email": "Raolane",
  "contact": "226 west street",
  "streetnumber": "226 west street",
   "streetname": "226 west street",
}
