@echo off
REM Generated by trunk tool 'checkov'
set PATH=C:\Users\222417961\AppData\Local\trunk\tools\checkov\3.2.490-0f1c134a8e836c84dc7f511c1ec0ea11/bin;C:\Users\222417961\AppData\Local\trunk\tools\checkov\3.2.490-0f1c134a8e836c84dc7f511c1ec0ea11/Scripts;C:\Users\222417961\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\222417961\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\222417961\AppData\Local\trunk\tools\checkov\3.2.490-0f1c134a8e836c84dc7f511c1ec0ea11

start /w /b checkov %*
