@echo off
REM Generated by trunk tool 'dotenv-linter'
set PATH=C:\Users\222417961\AppData\Local\trunk\tools\dotenv-linter\3.3.0-45c3e098335f48d29fb64b46051516fe;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b dotenv-linter %*
