@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\222417961\AppData\Local\trunk\tools\trufflehog\3.90.13-e46740766b963854c2ebadfd212340f3;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\222417961\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
