action_id: trunk-upgrade-available
date: 2025-11-07 09:45:02
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1762508702
full_timestamp:
  nanos: 257214000
  seconds: 1762508702
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
