action_id: trunk-upgrade-available
date: 2025-11-06 10:39:51
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1762425591
full_timestamp:
  nanos: 480024000
  seconds: 1762425591
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
