action_id: trunk-upgrade-available
date: 2025-11-08 17:54:18
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: .trunk/trunk.yaml
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1762624458
full_timestamp:
  nanos: 672325000
  seconds: 1762624458
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
