action_id: trunk-upgrade-available
date: 2025-11-11 14:08:23
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1762870103
full_timestamp:
  nanos: 302041000
  seconds: 1762870103
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
